
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Aa123456
  neo4j:
    uri: bolt://127.0.0.1:7473
    authentication:
      username: neo4j
      password: Aa123456



Logging:
  level:
    com.wms: error